services :
  mongodb-example :
    image : mongo:latest
    container_name : mongodb-example
    ports :
      - "27017:27017"
    environment :
      MONGO_INITDB_ROOT_USERNAME : fathirrzkii
      MONGO_INITDB_ROOT_PASSWORD : fathirrzkii
      MONGO_INITDB_DATABASE : admin