FROM alpine:3

LABEL author = "Fathir Rizki Fadillah"
LABEL company = "TON LABS" github_author = "https://github.com/fathirrizkifadillah"

RUN mkdir hello
RUN echo "hello World" > "hello/world.txt"

CMD cat "hello/world.txt"